# NutriWise Food Database
from typing import Dict, List, Any

FOOD_DATABASE: Dict[str, Dict[str, Any]] = {
    "paneer sandwich": {
        "name": "Paneer Tikka Sandwich",
        "category": "Sandwiches & Wraps",
        "serving_size": "1 sandwich (220g)",
        "calories": 385,
        "protein_g": 18.5,
        "carbs_g": 42.0,
        "fat_g": 15.2,
        "fiber_g": 4.5,
        "sugar_g": 3.8,
        "sodium_mg": 520.0,
        "vitamins": ["Calcium", "Vitamin A", "Phosphorus", "Vitamin B12"],
        "allergens": ["dairy", "gluten"],
        "glycemic_index": "medium",
        "tags": ["vegetarian", "protein_source", "breakfast", "lunch"]
    },
    "poha with curd": {
        "name": "Vegetable Poha with Curd",
        "category": "Traditional Breakfast",
        "serving_size": "1 bowl (250g)",
        "calories": 290,
        "protein_g": 8.5,
        "carbs_g": 48.0,
        "fat_g": 7.0,
        "fiber_g": 4.2,
        "sugar_g": 4.1,
        "sodium_mg": 380.0,
        "vitamins": ["Iron", "Vitamin C", "Probiotics", "B-Complex"],
        "allergens": ["dairy"],
        "glycemic_index": "medium",
        "tags": ["vegetarian", "breakfast", "easy_digest"]
    },
    "dal rice vegetables": {
        "name": "Dal Tadka with Steamed Rice & Stir-fry Sabzi",
        "category": "Balanced Main Meal",
        "serving_size": "1 thali portion (400g)",
        "calories": 480,
        "protein_g": 16.0,
        "carbs_g": 78.0,
        "fat_g": 11.5,
        "fiber_g": 8.2,
        "sugar_g": 5.0,
        "sodium_mg": 610.0,
        "vitamins": ["Folate", "Iron", "Potassium", "Vitamin A"],
        "allergens": [],
        "glycemic_index": "medium",
        "tags": ["vegetarian", "vegan", "lunch", "dinner", "wholesome"]
    },
    "fruit roasted chana": {
        "name": "Seasonal Mixed Fruit & Roasted Chana",
        "category": "Healthy Snack",
        "serving_size": "1 bowl (180g)",
        "calories": 195,
        "protein_g": 8.0,
        "carbs_g": 34.0,
        "fat_g": 3.0,
        "fiber_g": 6.8,
        "sugar_g": 16.0,
        "sodium_mg": 95.0,
        "vitamins": ["Vitamin C", "Potassium", "Dietary Fiber"],
        "allergens": [],
        "glycemic_index": "low",
        "tags": ["vegetarian", "vegan", "snack", "clean_fuel"]
    },
    "roti paneer vegetables": {
        "name": "Multigrain Roti with Paneer Bhurji & Mixed Veg",
        "category": "High Protein Dinner",
        "serving_size": "2 rotis + 150g sabzi (350g)",
        "calories": 440,
        "protein_g": 22.0,
        "carbs_g": 48.0,
        "fat_g": 17.5,
        "fiber_g": 7.5,
        "sugar_g": 4.2,
        "sodium_mg": 540.0,
        "vitamins": ["Calcium", "Vitamin A", "Zinc", "Magnesium"],
        "allergens": ["dairy", "gluten"],
        "glycemic_index": "low",
        "tags": ["vegetarian", "high_protein", "dinner"]
    },
    "greek salad": {
        "name": "Mediterranean Greek Salad with Feta",
        "category": "Salads",
        "serving_size": "1 large bowl (300g)",
        "calories": 260,
        "protein_g": 9.5,
        "carbs_g": 14.0,
        "fat_g": 18.0,
        "fiber_g": 5.0,
        "sugar_g": 6.2,
        "sodium_mg": 480.0,
        "vitamins": ["Vitamin K", "Vitamin C", "Antioxidants"],
        "allergens": ["dairy"],
        "glycemic_index": "low",
        "tags": ["vegetarian", "keto_friendly", "fiber_rich"]
    },
    "chicken biryani": {
        "name": "Chicken Dum Biryani with Cucumber Raita",
        "category": "Rice & Entrees",
        "serving_size": "1 plate (380g)",
        "calories": 590,
        "protein_g": 32.0,
        "carbs_g": 68.0,
        "fat_g": 20.0,
        "fiber_g": 4.0,
        "sugar_g": 3.5,
        "sodium_mg": 780.0,
        "vitamins": ["Niacin", "Selenium", "Phosphorus", "Vitamin B6"],
        "allergens": ["dairy"],
        "glycemic_index": "high",
        "tags": ["non_vegetarian", "high_protein", "heavy_meal"]
    },
    "pizza slice": {
        "name": "Cheese & Vegetable Pizza (2 Slices)",
        "category": "Fast Food",
        "serving_size": "2 medium slices (210g)",
        "calories": 540,
        "protein_g": 18.0,
        "carbs_g": 64.0,
        "fat_g": 23.0,
        "fiber_g": 3.2,
        "sugar_g": 7.0,
        "sodium_mg": 1120.0,
        "vitamins": ["Calcium", "Vitamin A"],
        "allergens": ["dairy", "gluten"],
        "glycemic_index": "high",
        "tags": ["cheat_meal", "high_sodium", "processed"]
    },
    "cold drink": {
        "name": "Regular Cola Soft Drink",
        "category": "Beverages",
        "serving_size": "1 can (330ml)",
        "calories": 140,
        "protein_g": 0.0,
        "carbs_g": 38.0,
        "fat_g": 0.0,
        "fiber_g": 0.0,
        "sugar_g": 38.0,
        "sodium_mg": 40.0,
        "vitamins": [],
        "allergens": [],
        "glycemic_index": "very_high",
        "tags": ["empty_calories", "high_sugar"]
    },
    "oatmeal berries": {
        "name": "Rolled Oats Bowl with Berries, Chia & Almond Milk",
        "category": "Superfood Breakfast",
        "serving_size": "1 bowl (280g)",
        "calories": 310,
        "protein_g": 12.0,
        "carbs_g": 52.0,
        "fat_g": 6.5,
        "fiber_g": 9.5,
        "sugar_g": 9.0,
        "sodium_mg": 110.0,
        "vitamins": ["Beta-Glucan", "Manganese", "Vitamin E", "Antioxidants"],
        "allergens": ["nuts"],
        "glycemic_index": "low",
        "tags": ["vegan", "vegetarian", "heart_healthy", "high_fiber"]
    },
    "protein bar label": {
        "name": "Whey Crisp High Protein Bar (Packaged Label)",
        "category": "Packaged Supplements",
        "serving_size": "1 bar (60g)",
        "calories": 210,
        "protein_g": 20.0,
        "carbs_g": 22.0,
        "fat_g": 6.0,
        "fiber_g": 8.0,
        "sugar_g": 2.0,
        "sodium_mg": 180.0,
        "vitamins": ["Calcium", "Iron", "Vitamin B6"],
        "allergens": ["dairy", "soy", "nuts"],
        "glycemic_index": "low",
        "tags": ["packaged_food", "label_scan", "high_protein", "sports"]
    },
    "potato chips label": {
        "name": "Classic Salted Potato Chips (Packaged Label)",
        "category": "Packaged Snack",
        "serving_size": "1 bag (50g)",
        "calories": 270,
        "protein_g": 3.0,
        "carbs_g": 28.0,
        "fat_g": 17.0,
        "fiber_g": 1.5,
        "sugar_g": 0.5,
        "sodium_mg": 390.0,
        "vitamins": ["Potassium"],
        "allergens": [],
        "glycemic_index": "high",
        "tags": ["packaged_food", "label_scan", "processed", "high_fat"]
    }
}
